name: "allow-pr-merge"

on:
  workflow_run:
    workflows: ["test-pyall"]    # MUST match the 'name:' in .github/workflows/test-all.yml
    types: [completed]

permissions:
  contents: read

jobs:
  successful-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Allow merge
        run: echo "test-pyall succeeded for run ${{ github.event.workflow_run.id }}"