name: "01 - Run Tests (Latest Supported Version)"

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  vars:
    uses: ./.github/workflows/ci-variables.yml

  # security-scan:
  #   needs: vars
  #   uses: ./.github/workflows/security-scan.yml
  #   permissions:
  #     contents: read
  #     security-events: write
  #   secrets: inherit

  run-tests:
    needs: vars
    uses: ./.github/workflows/test-with-python-versions-reusable.yml
    with:
      python_versions: ${{ needs.vars.outputs.python_versions_latest }}
      fail_fast: false
    secrets: inherit
