name: "01 - Run Tests (Latest Supported Version)"

on:
  workflow_dispatch: {}
  workflow: {}
permissions:
  contents: read

jobs:
  vars:
    uses: ./.github/workflows/ci-variables.yml

  security-scan:
    needs: vars
    uses: ./.github/workflows/security-scan.yml
    secrets: inherit

  run-tests:
    needs: vars
    uses: ./.github/workflows/test-with-python-versions-reusable.yml
    with:
      python_versions: ${{ toJson([ needs.vars.outputs.python_version_latest ]) }}
    secrets: inherit